name: learn-github-actions
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      with:
        node-version: '14'
      - run: npm i
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm test